server:
  servlet:
    context-path: /workflow
  port: 8445

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bref_activiti?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  # activiti default configuration
  activiti:
    database-schema-update: false
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/
    # process-definition-location-suffixes:
    #   - **.bpmn
    #   - **.bpmn20.xml
    history-level: full
    activityFontName: 宋体
    labelFontName: 宋体
    
# mybatis 配置
mybatis:
  mapper-locations: classpath:/com/brt/bref/workflow/dao/*Dao.xml,com/brt/bref/common/dao/*Dao.xml
  # type-aliases-package: com.brt.bref.user.svc.entity
  # mapper-locations: classpath:com/brt/bref/user/svc/dao/**/*.xml
  # 配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性
  configuration:
    map-underscore-to-camel-case: true
# PageHelper 配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

security:
  oauth2:
    client:
      client-id: workflow
      client-secret: workflow
      access-token-uri: http://127.0.0.1:8411/auth/oauth/token
      user-authorization-uri: http://127.0.0.1:8411/auth/oauth/authorize
      grant-type: client_credentials
      scope: server
    resource:
      id: workflow
      token-info-uri: http://127.0.0.1:8411/auth/oauth/check_token
      user-info-uri: http://127.0.0.1:8411/auth/user
      prefer-token-info: false    
    